In [1]:
import numpy as np
import pandas as pd
import numpy.linalg as la

In [2]:
size = 20*1000
X = np.random.random((size, size))
X.round(2)

array([[0.28, 0.44, 0.96, ..., 0.29, 0.57, 0.7 ],
       [0.89, 0.66, 0.38, ..., 0.33, 0.84, 0.85],
       [0.38, 0.42, 0.09, ..., 0.7 , 0.86, 0.9 ],
       ...,
       [0.87, 0.68, 0.19, ..., 0.27, 0.23, 0.96],
       [0.73, 0.12, 0.08, ..., 0.47, 0.51, 0.  ],
       [0.18, 0.72, 0.94, ..., 0.35, 0.86, 0.42]])

In [3]:
U,S,V = la.svd(X,False,True)
U,S,V

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([2.4446376e-316, 4.0087941e-316, 0.0000000e+000, ...,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [1]:
not np.any(U)

NameError: name 'np' is not defined

In [1]:
import numpy as np
import pandas as pd
import numpy.linalg as la
import datetime
p_size = 1000
p_seconds = .67

#svd
#error 20*1000,19K,18K,17K
#16K is OK

#eigh
# ok at 17K,18K, 20K, 22K (failed before) 
# Fail at 24
#memory at 3

for size in [1000,5000,24*1000,25*1000,26*1000,27*1000]:
    predict = p_seconds * (float(size)/p_size)**3
    print("Starting {0}x{0}. Predict {1} seconds".format(size,predict))
    start = datetime.datetime.now()
    np.random.seed(0)
    X = np.random.randn(size, size).astype(np.float)# + np.random.randn(row_count, col_count)
    #X = np.random.random((size, size))
    #U,s,V = la.svd(X,False,True)
    S,V = la.eigh(X.T.dot(X))
    delta = datetime.datetime.now() - start
    print("Done in {0} seconds. Next will check.".format(delta.total_seconds())) 
    if not np.any(V):
        print("FAIL Expect U,V to be non-zero")
    else:
        delta.total_seconds()
        print("\tChecks out")    
        p_size = size
        p_seconds = delta.total_seconds()
    

Starting 1000x1000. Predict 0.67 seconds
Done in 0.321 seconds. Next will check.
	Checks out
Starting 5000x5000. Predict 40.125 seconds
Done in 17.475 seconds. Next will check.
	Checks out
Starting 24000x24000. Predict 1932.5952 seconds
Done in 151.7 seconds. Next will check.
FAIL Expect U,V to be non-zero
Starting 25000x25000. Predict 2184.375 seconds
Done in 207.495 seconds. Next will check.
FAIL Expect U,V to be non-zero
Starting 26000x26000. Predict 2457.1248 seconds
Done in 246.799 seconds. Next will check.
FAIL Expect U,V to be non-zero
Starting 27000x27000. Predict 2751.6834 seconds
Done in 246.478 seconds. Next will check.
FAIL Expect U,V to be non-zero
